#!/usr/bin/env bash
#Script that accepts 2 arguments, domain and subdomain and returns The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION].
if [ $# -eq 2 ]
then
     domain="$2.$1"
else 
  domain="www.$1 lb-01.$1 web-01.$1 web-02.$1"
fi
dig "$domain" | awk '/ANSWER SECTION:/{getline; split($0,a,"."); print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
