#!/usr/bin/env bash
#Script installs nginx server.
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html -R
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo service nginx start
