#!/usr/bin/env bash
#Script installs nginx server.
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx start
