#!/usr/bin/env bash
#Script changes redirection.
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html -R
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/josh-94 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
