#!/usr/bin/env bash
#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that
#contains the string Ceci n'est pas une page.
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html -R
echo 'Hello World' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/error.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/josh-94 permanent;/" /etc/nginx/sites-available/default
sudo sed -i "s/^server\s{/server {\n\terror_page 404 \/error.html;/1" /etc/nginx/sites-available/default
sudo sed -i "s/^server\s{/server {\n\tadd_header X-Served-By $HOSTNAME;/1" /etc/nginx/sites-available/default
sudo service nginx restart
