#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

## Install HAproxy
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get install haproxy -y
sudo chown -R ubuntu /etc/haproxy
## Configure haproxy.cfg
echo '''
frontend myfrontend
        bind *:80
        mode http
        default_backend myservers

backend myservers
        balance roundrobin
        server 3686-web-01 34.74.168.72:80 check
        server 3686-web-02 54.82.79.23:80 check''' >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
