#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
ifconfig | grep -Po 'inet \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | cut -d " " -f2
