#!/usr/bin/env bash
#Bash script to run nginx server as nginx user"
sudo chmod 644 /etc/nginx/nginx.conf
pkill -f apache2
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
