#!/usr/bin/env bash
#Bash script to run nginx server as nginx user"
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
